runtime: go
api_version: go1

handlers:

- url: /assets/(.*\.(eot|scss|less|otf))
  static_files: assets/(.*\.(eot|scss|less|otf))
  upload: assets/(.*\.(eot|scss|less|otf))
  mime_type: application/octet-stream
  http_headers:
    Strict-Transport-Security: max-age=86400; includeSubDomains

- url: /assets
  static_dir: assets
  http_headers:
    Strict-Transport-Security: max-age=86400; includeSubDomains

- url: /dist
  static_dir: dist
  http_headers:
    Strict-Transport-Security: max-age=86400; includeSubDomains

- url: /backend
  static_dir: admin-dist/backend
  http_headers:
     Strict-Transport-Security: max-age=86400; includeSubDomains


- url: /(robots\.txt|humans\.txt|crossdomain\.xml|sitemap\.xml)
  static_files: assets/\1
  upload: assets/(robots\.txt|humans\.txt|crossdomain\.xml|sitemap\.xml)

#favicon
- url: /favicon.ico
  static_files: assets/images/favicon.ico
  upload: assets/images/(favicon\.ico)

# guser only allowed endpoints
- url: /backend/*
  static_files: admin-dist/backend/index.html
  upload: admin-dist/backend/index.html
  secure: always

- url: /api/superuser/.*
  script: _go_app
  login: required
  secure: always

- url: /.*
  script: _go_app

skip_files:
 - ^(.*/)?#.*#$
 - ^(.*/)?.*~$
 - ^(.*/)?.*/RCS/.*$
 - ^(.*/)?\..*$
 - ^.*idea(/.*)?
 - ^.*node_modules(/.*)?
 - ^.*scss(/.*)?
 - ^backend(/.*)?
